language: rust
rust:
    - stable
    - beta
    - nightly
arch:
    - amd64
    - arm64
    - ppc64le
env:
    - CRATE=im
    - CRATE=im-rc

cache:
    directories:
        - /home/travis/.rustup
        - /home/travis/.cargo
        - /home/travis/target

install:
    - rustup update
    - mkdir -p .cargo && echo '[build]' > .cargo/config && echo 'target-dir = "/home/travis/target"'
      >> .cargo/config
    - cargo install cargo-make; true
    - cargo make prepare-release

script: cd dist/$CRATE; cargo test
